# Generated by Django 6.0.6 on 2026-06-27 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('earthquake_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('place', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('depth', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'earthquake',
                'ordering': ['-time'],
            },
        ),
    ]
