# Generated by Django 5.2.7 on 2026-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateField()),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitation_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('data_type', models.CharField(choices=[('historical', 'Historical'), ('forecast', 'Forecast')], default='historical', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_record',
                'ordering': ['-date'],
                'unique_together': {('latitude', 'longitude', 'date', 'data_type')},
            },
        ),
    ]
